name: Run lighthouse CI When Push

on:
  push:
    branches: [ development ]

jobs:
  lhci:
    name: Lighthouse CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install packages
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI!"
